
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
