apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - host: demo.com
    http:
      paths:
      - path: /foo
        backend:
          service:
            name: nginx-service
            port:
              number: 8080

