apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30007

---
# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#  name: my-service-1
#  label:
#    kubernetes.io/service-name: my-service
# addressType: IPv4
# spec:
#  - name: ""
#    appProtocol: http
#    protocol: TCP
#    port: 9376
# endpoints:
#  - addresses:
#      - "10.4.5.6"
#      - "10.1.2.3"
